import { readdir } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

// Generate a self-contained Zig module. Bytes are compiled into .rodata;
// no runtime files, temp directories, native addons or helper processes.
const root = fileURLToPath(new URL("../dist/", import.meta.url));
const output = process.argv[2] ?? fileURLToPath(new URL("../ui-assets.generated.zig", import.meta.url));
const files = (await readdir(root, { recursive: true, withFileTypes: true }))
  .filter((entry) => entry.isFile())
  .sort((left, right) => {
    const a = join(left.parentPath, left.name);
    const b = join(right.parentPath, right.name);
    return a < b ? -1 : a > b ? 1 : 0;
  });
const declarations: string[] = [];
const entries: string[] = [];
const types: Record<string, string> = {
  html: "text/html; charset=utf-8", js: "text/javascript; charset=utf-8",
  css: "text/css; charset=utf-8", svg: "image/svg+xml", png: "image/png",
  jpg: "image/jpeg", webp: "image/webp", ico: "image/x-icon", woff2: "font/woff2",
};
for (const entry of files) {
  const path = relative(root, join(entry.parentPath, entry.name)).replaceAll("\\", "/");
  if (!/^[a-zA-Z0-9_./-]+$/.test(path)) throw new Error(`Unsupported asset path: ${path}`);
  const bytes = await Bun.file(join(root, path)).bytes();
  const id = `asset${declarations.length}`;
  declarations.push(`const ${id} = [_]u8{${Array.from(bytes, (byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(",")}};`);
  const type = types[path.split(".").pop()!] ?? "application/octet-stream";
  entries.push(`.{ .path = ${JSON.stringify(path === "index.html" ? "/" : `/${path}`)}, .body = &${id}, .content_type = ${JSON.stringify(type)} }`);
}
if (!files.some((entry) => entry.name === "index.html")) throw new Error("Missing frontend index.html");
await Bun.write(output, `// Generated by Bun after the Vite+ build.\nconst std = @import("std");\npub const Asset = struct { path: []const u8, body: []const u8, content_type: []const u8 };\n${declarations.join("\n")}\nconst assets = [_]Asset{${entries.join(",\n")}};\npub fn get(path: []const u8) ?Asset { for (assets) |asset| { if (std.mem.eql(u8, path, asset.path)) return asset; } return null; }\n`);
